apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: production

bases:
- ../../base

replicas:
- name: my-app
  count: 5

images:
- name: nginx
  newTag: 1.25-alpine

patchesStrategicMerge:
- patch-deployment.yaml

commonLabels:
  environment: production
