apiVersion: tekton.dev/v1beta1
kind: Task
metadata:
  name: docker-build
  namespace: default
spec:
  description: Build et push d'une image Docker
  workspaces:
    - name: source
  params:
    - name: image
      type: string
      description: Nom complet de l'image (registry/name:tag)
    - name: dockerfile
      type: string
      default: Dockerfile
      description: Chemin vers le Dockerfile
  steps:
    - name: build-and-push
      image: gcr.io/kaniko-project/executor:latest
      workingDir: $(workspaces.source.path)
      env:
        - name: DOCKER_CONFIG
          value: /tekton/home/.docker
      command:
        - /kaniko/executor
      args:
        - --dockerfile=$(params.dockerfile)
        - --context=$(workspaces.source.path)
        - --destination=$(params.image)
        - --skip-tls-verify
        - --cache=true
      volumeMounts:
        - name: docker-config
          mountPath: /tekton/home/.docker
  volumes:
    - name: docker-config
      emptyDir: {}
